sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t callumbennett/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true callumbennett/docker-react npm run test